@baseUrl = http://localhost:3000
@categoryId = 1

############################################################
# CATEGORY SERVICE
############################################################

### Get all categories
GET {{baseUrl}}/category
Content-Type: application/json

###

### Get a specific category by ID
GET {{baseUrl}}/category/{{categoryId}}
Content-Type: application/json

###
