import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function getRandomQuery() {
  const words = [
    "Science",
    "Fantasy",
    "Adventure",
    "Mystery",
    "Biography",
    "Travel",
    "Comics",
    "Romance",
    "History",
    "Children",
    "Young adult",
    "Thriller",
    "Cooking",
    "Music",
    "Technology",
    "Nature",
    "Animals",
    "Space",
    "Friendship",
    "Family",
    "Crime",
    "Humor",
    "Drama",
    "Science fiction",
    "Horror",
    "Magic",
    "Mythology",
    "Education",
  ];
  return words[Math.floor(Math.random() * words.length)];
}

export const horrorKeywords = [
  "horror",
  "horror fiction",
  "horror tales",
  "supernatural",
  "ghost",
  "ghost stories",
  "paranormal",
  "occult",
  "vampire",
  "vampires",
  "werewolf",
  "werewolves",
  "demon",
  "demons",
  "zombie",
  "zombies",
  "dark fantasy",
  "psychological horror",
  "creepy",
  "macabre",
  "spooky",
  "thriller",
  "suspense",
  "terror",
  "nightmare",
  "monster",
  "monsters",
  "gothic",
  "gothic fiction",
  "slasher",
  "possession",
  "haunted",
  "haunting",
  "evil",
  "curse",
  "cursed",
  "witch",
  "witches",
  "black magic",
  "blood",
  "killer",
  "serial killer",
  "murder",
  "mystery",
  "fear",
];

export const loveKeywords = [
  "love",
  "romance",
  "romantic",
  "romantic fiction",
  "love stories",
  "contemporary romance",
  "historical romance",
  "young adult romance",
  "chick lit",
  "relationship",
  "relationships",
  "dating",
  "wedding",
  "marriage",
  "passion",
  "affair",
  "heartbreak",
  "soulmate",
  "forbidden love",
  "romantic comedy",
  "rom-com",
  "erotic romance",
  "new adult romance",
  "sweet romance",
  "second chance romance",
  "friends to lovers",
  "enemies to lovers",
  "love triangle",
  "first love",
  "crush",
  "flirt",
  "courtship",
  "honeymoon",
  "valentine",
  "secret admirer",
  "proposal",
  "romantic suspense",
  "romantic drama",
  "romantic adventure",
];

export const fantasyKeywords = [
  "fantasy",
  "fantasy fiction",
  "epic fantasy",
  "high fantasy",
  "dark fantasy",
  "urban fantasy",
  "magic",
  "magical",
  "wizards",
  "wizard",
  "witches",
  "sorcery",
  "enchantment",
  "spells",
  "dragons",
  "dragon",
  "elves",
  "dwarves",
  "mythical creatures",
  "quest",
  "adventure",
  "sword and sorcery",
  "magical realism",
  "fairy tale",
  "fairy tales",
  "folklore",
  "mythology",
  "mythological",
  "legends",
  "medieval fantasy",
  "fantasy adventure",
  "heroic fantasy",
  "portal fantasy",
  "alternate worlds",
  "parallel worlds",
  "magical kingdom",
  "enchanted",
  "mystical",
  "supernatural fiction",
];
